### ISSUE TITLE
! pip install inferactively-pymdp 

### ISSUE THREAD

**Issue by vala1958** [infer-actively/pymdp#113]
Dear researchers

Unfortunatelly this wonderfull pyton toolbox for active inference cannot be opened in colab since Thursday 23.3.23 evening. What can be done?

I hope this can be fixed soon! Thank you in advance.

Best
Susanne Valavanis

**Comment by conorheins** [comment]
Thank you for bringing this to our attention! I will get on this ASAP and try to fix it. 

In the meantime, you should be able to perform a local "dev install" of the master branch of `pymdp`, by using the following commands in a fresh Google Colab environment to get it working:

```
!git clone https://github.com/infer-actively/pymdp.git
%cd pymdp/
!pip install -e ./ # This will install pymdp as a local dev package
```

This way you circumvent installing the version of `pymdp` registered on PyPi, which I suspect has an error in the `setup.py` file (see [here](https://github.com/infer-actively/pymdp/pull/110)), which I think is causing a conflict with new basic dependencies that are pre-loaded on starting up a google colab instance. For example, maybe Google has updated the base version of Python that is used in Colab?

**Comment by conorheins** [comment]
I think it should now be fixed, I verified that I could pip install it in Google Colab. Please see the latest release here for details on changes to the `setup.py` file (importantly, including a bug discovered by @SWauthier ): https://github.com/infer-actively/pymdp/releases/tag/v0.0.7.1

**Comment by vala1958** [comment]
Ohh thank you very much! I‘m not experienced in deinstalling/installing packages. But I will try it tomorrow. I assume with fresh Environment you mean that I just start a new colab file in my account?I will inform you about the success tomorrow (not before 3 pm)Have a nice evening!Best Susanne Von meinem iPhone gesendetAm 25.03.2023 um 18:03 schrieb conorheins ***@***.***>:﻿
Thank you for bringing this to our attention! I will get on this ASAP and try to fix it.
In the meantime, you should be able to perform a local "dev install" of the master branch of pymdp, by using the following commands in a fresh Google Colab environment to get it working:
!git clone https://github.com/infer-actively/pymdp.git
%cd pymdp/
!pip install -e ./ # This will install pymdp as a local dev package

This way you circumvent installing the version of pymdp registered on PyPi, which I suspect has an error in the setup.py file (see here), which I think is causing a conflict with new basic dependencies that are pre-loaded on starting up a google colab instance. For example, maybe Google has updated the base version of Python that is used in Colab?
