### ISSUE TITLE
an error in the official documentation

### ISSUE THREAD

**Issue by Sangxiaofu** [infer-actively/pymdp#125]
Dear sir，
In the official document "Active Inference Demo: Epistemological Chains",

Starting with the 0-th modality, the Location observation modality: A[0]

A[0] = np.tile(np.expand_dims(np.eye(num_grid_points), (-2, -1)), (1, 1, num_states[1], num_states[2]))

i run it but with the error "A matrix is not normalized (i.e. A.sum(axis = 0) must all be equal to 1.0)",this looks initialized but not normalized

**Comment by conorheins** [comment]
Hi @Sangxiaofu -- I see you closed this issue. I was planning on looking into this, unless you can confirm that it's not a problem anymore?
