### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by osaaso3** [infer-actively/pymdp#33]
Hi
I came up with thois message when running agent-demo (tmaze works fine):

![image](https://user-images.githubusercontent.com/74146647/120811746-8f344880-c561-11eb-929e-fa6db6f3ec7b.png)

**Comment by conorheins** [comment]
Hi @osaaso3, thanks for identifying this. It was a bug introduced by the fact that actions are now returned as floats, not integers. So I've fixed it by converting to int during sampling (this bug also occurs during `control.get_expected_states()` if the `control` variable is not converted to an `int`).

**Comment by conorheins** [comment]
Feel free to comment here if the issue still persists. If I don't hear back in 1-2 days I'll assume the fix works on your end and I'll close the issue.

**Comment by osaaso3** [comment]
Thanks conorheins,
I am new to python, BTW. Another error message I get:
![image](https://user-images.githubusercontent.com/74146647/121178179-7b475a00-c873-11eb-9fd3-426760afe9e9.png)

**Comment by conorheins** [comment]
this is on the T-maze, right? I've just fixed the action indexing there as well -- sorry about this, I haven't been actively maintaining the demos as much as I should be :)

**Comment by osaaso3** [comment]
Thanks again, now T-maze-Demo (not Tmaze-Learning) and agent-demo work fine. But other examples have errors, like the previous one which might be warning or normalization error for Matrix-demos:
![image](https://user-images.githubusercontent.com/74146647/121255562-cc316f80-c8c0-11eb-9ebc-8541587ccc58.png)
 or this NameError:
![image](https://user-images.githubusercontent.com/74146647/121255662-e8cda780-c8c0-11eb-97af-26bf554b313c.png)


Maybe my python settings are not good as I get this for environment settings:
![image](https://user-images.githubusercontent.com/74146647/121254758-e28afb80-c8bf-11eb-863c-6b3fb9dd0056.png)
You can close the issue but a step by step guide for the required software can help. I use win64 anaconda/Jupyter and online myBinder.

**Comment by conorheins** [comment]
hi sorry for the late reply on this -- i will close the issue for now, but thanks for alerting me to the issues with the environment. i will look into it
