### ISSUE TITLE
Action indices need to be cast to `int` in T-maze learning demo

### ISSUE THREAD

**Issue by conorheins** [infer-actively/pymdp#40]
Thanks @conorheins and @Arun-Niranjan,
things getting better. 
The A-matrix worked with your my-A-matrix but B-matrix was not fixed I think. A sample pandas matrix might help.
An issue remained with T-maze-learning (T-maze-demo works fine), that I pase it here but I can open an issue if needed.
![image](https://user-images.githubusercontent.com/74146647/125197172-e40a6380-e271-11eb-931e-de62473c61b2.png)

Best

_Originally posted by @osaaso3 in https://github.com/infer-actively/pymdp/issues/26#issuecomment-877800539_

**Comment by osaaso3** [comment]
Hi Conor,
This issue hasn't been solved. It happens because normalization adds nose to zero or something like that. 
Please fix it. You can recreate the error on Google Colab for example.
Best

**Comment by conorheins** [comment]
You're right this is a premature closure - I am about to push a refactor where that issue doesn't exist anymore, and more fundamental changes are made to that demo anyway (right now it's not quite functioning correctly). So I wouldn't recommend running the tmaze learning demo until the refactor is pushed anyway (which will be either tomorrow or within a few days max).

**Comment by osaaso3** [comment]
Thanks Conor,
In the meantime, I converted action to int and it works but to make sure I will compare the results to yours...
Good to hear about updates though.
I'll try your new version.

**Comment by conorheins** [comment]
Hi @osaaso3,
the refactor has now been pushed and the T-maze learning demo should be use-able and bug-free. 

We will update the documentation / main page of the repo soon as well to reflect new changes to the repository :)
