### ISSUE TITLE
Full API documentation

### ISSUE THREAD

**Issue by seankmartin** [infer-actively/pymdp#67]
Hi!

I think it would be useful to provide full API documentation for your package on your [RTD website](https://pymdp-rtd.readthedocs.io/en/latest/).
For example, I think the agent class and the envs subpackage are quite important, but I can't find API docs for them on the site.
I'd find it easier to follow if they were listed in the modules section of the site, or even if you wanted to provide a separate full API documentation section that would work too I think.
Thanks!

**Comment by conorheins** [comment]
Thanks again for these great suggestions @seankmartin -- we've already addressed them in the review a few weeks back, but I'm just commenting again to confirm that we've closed this issue now
