### ISSUE TITLE
einsum while calculating free energy

### ISSUE THREAD

**Issue by lqiang2003cn** [infer-actively/pymdp#98]
hi, guys, i have a question about calculating the free energy. While calculating einsum, why only sum to the first dim:

arg_list = [X, list(range(X.ndim))] + list(chain(*([x[xdim_i],[dims[xdim_i]]] for xdim_i in range(len(x))))) _**+ [[0]]**_

and then use:

spm_dot(likelihood, qs)[0] 

to fetch only the first level of s0 (suppose hidden state s is factorized as s0, s1, ... ) ? 

in my opinion, we should sum over all the tensor by removing the last _**+ [[0]]**_ and the Y should just be a scalar. 
am I totally wrong, if i am, please correct me, thanks a lot!

**Comment by lqiang2003cn** [comment]
> But I'm debating whether to make that an additional gating condition within spm_dot (with another if statement), or whether to just do it in-line in the calc_free_energy function...

spm_dot is used in many contexts and in some cases we do need the last `[[0]]`, so i guess `do it in-line in the calc_free_energy function` would be better.

**Comment by conorheins** [comment]
I fixed the bug, and have merged the resulting PR into master. Nice job again @lqiang2003cn for spotting this, and thank you. This is by far the most technically-nuanced error someone has noticed so far; I'm impressed that you managed to parse that line of preparation for the einsum arguments in `spm_dot` :)

Will close this issue upon release of pymdp `0.0.7`

**Comment by conorheins** [comment]
Closing now that  `v.0.0.7` is released
